version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: gatsby-cli
    versions:
    - 2.18.0
    - 2.19.0
    - 2.19.1
    - 2.19.2
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.4.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
    - 2.12.1
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.1
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.5
    - 2.32.6
    - 2.32.7
    - 2.32.8
    - 2.32.9
    - 3.0.2
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.11.0
    - 2.12.0
    - 2.12.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 2.14.2
    - 2.14.3
  - dependency-name: gatsby-plugin-matomo
    versions:
    - 0.9.0
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: "@material-ui/styles"
    versions:
    - 4.11.3
    - 4.11.4
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.9.0
  - dependency-name: gatsby-plugin-webfonts
    versions:
    - 2.0.0
