language: node_js
os: linux
dist: xenial
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - chmod +x ./tools/cname.sh
  - ./tools/cname.sh
  - yarn build
deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: develop